theme: minima
title: Yangfan250's Professional Portfolio
description: Physics undergraduate at the University of Connecticut with interests in quantum physics, quantum computing.
author: Yangfan250
